version: '3.8'

services:
  evidently:
    build: .
    volumes:
      - ../data:/app/data
      - report_data:/app/reporting  # Shared volume for report data
    ports:
      - "8001:8000"  
      - "8501:8501"

volumes:
  report_data: