<<<<<<< HEAD
version: '3.8'

networks:
  prod_net:
    driver: bridge

services:
  fastapi_serving:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_model_serving
    volumes:
      - ../artifacts:/app/artifacts
      - ../data:/app/data
      - ../scripts:/app/scripts
    ports:
      - "8000:8000"
    working_dir: /app
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - prod_net

=======
version: '3.8'

networks:
  prod_net:
    driver: bridge

services:
  fastapi_serving:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_model_serving
    volumes:
      - ../artifacts:/app/artifacts
      - ../data:/app/data
      - ../scripts:/app/scripts
    ports:
      - "8000:8000"
    working_dir: /app
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - prod_net

>>>>>>> 2f43fb2 (commit)
